### ISSUE TITLE
The sensor stops working properly when it is on the metal part for a long time

### ISSUE THREAD

**Issue by markoAntonio1692** [pifactory/watermeter#2] opened 2022-04-08 23:52 UTC
Hi,
I also follow your project, and I have the problem that when the sensor is positioned in the metal part for a long time, it returns to state 1 and it is as if it lost the detection range. How did you do to correct that error? I would appreciate it if you could upload your algorithm or tell me how to configure the sensor registers....By the way, a very good project. I congratulate you, you have earned my admiration. Greetings

**Comment by advorkovyy** [comment] 2022-04-09 00:30
Duplicate of issue #1

**Closed by advorkovyy** 2022-04-09 00:30 UTC
